# 💊 Medicine Recommendation System

## Personalized Healthcare & Medicine Recommendation System

This notebook predicts the patient's disease using the trained Random Forest model and provides personalized healthcare recommendations including medicines, diet, exercise, water intake, and precautions.

In [1]:
import pandas as pd
import numpy as np
import joblib

print("Libraries imported successfully!")

Libraries imported successfully!

## Step 2: Load Trained Model

Load the trained Random Forest model for disease prediction.

In [17]:
import joblib

model = joblib.load("../../models/random_forest_model.pkl")
label_encoder = joblib.load("../../models/disease_label_encoder.pkl")

print("Model Loaded Successfully!")
print(model.feature_names_in_)

Model Loaded Successfully!
['fever' 'cough' 'fatigue' 'difficulty_breathing' 'age' 'gender'
 'blood_pressure' 'cholesterol_level' 'age_scaled' 'bp_scaled'
 'chol_scaled' 'risk_level']

In [3]:
print(model.feature_names_in_)

['fever' 'cough' 'fatigue' 'difficulty_breathing' 'age' 'gender'
 'blood_pressure' 'cholesterol_level' 'age_scaled' 'bp_scaled'
 'chol_scaled' 'risk_level']

## Step 3: Load Dataset

Load the processed healthcare dataset to retrieve the feature names required by the trained model.

In [4]:
df = pd.read_csv("../../data/processed/processed_dataset.csv")

df.head()

,disease,fever,cough,fatigue,difficulty_breathing,age,gender,blood_pressure,cholesterol_level,outcome_variable,age_scaled,bp_scaled,chol_scaled,risk_level
0,56,1,0,1,1,-2.127676,0,0,1,1,-2.091160,-2.419529,-0.576777,1
1,24,0,1,1,0,-1.650559,0,1,1,0,-1.631964,-0.723915,-0.576777,1
2,37,0,1,1,0,-1.650559,0,1,1,0,-1.631964,-0.723915,-0.576777,2
3,6,1,1,0,1,-1.650559,1,1,1,1,-1.631964,-0.723915,-0.576777,2
4,37,1,0,0,0,-1.650559,0,1,1,1,-1.631964,-0.723915,-0.576777,2

## Step 4: Extract Feature Names

Retrieve the feature names used during model training. These will be used to prepare input data for prediction.

In [5]:
feature_names = model.feature_names_in_

print(feature_names)

['fever' 'cough' 'fatigue' 'difficulty_breathing' 'age' 'gender'
 'blood_pressure' 'cholesterol_level' 'age_scaled' 'bp_scaled'
 'chol_scaled' 'risk_level']

## Step 5: Medicine Recommendation Database

Create a healthcare recommendation database that maps diseases to medicines, diet plans, exercise routines, hydration guidance, and precautions.

In [6]:
recommendation_db = {
    "Influenza": {
        "Medicine": "Paracetamol",
        "Diet": "Warm soup and fruits",
        "Exercise": "Light walking",
        "Water": "3 Litres/day",
        "Precautions": "Take adequate rest"
    },

    "Asthma": {
        "Medicine": "Salbutamol Inhaler",
        "Diet": "Fresh vegetables",
        "Exercise": "Breathing exercises",
        "Water": "3 Litres/day",
        "Precautions": "Avoid dust and smoke"
    },

    "Diabetes": {
        "Medicine": "Metformin",
        "Diet": "Low sugar diet",
        "Exercise": "30 min walking",
        "Water": "2.5 Litres/day",
        "Precautions": "Monitor blood sugar"
    },

    "Hypertension": {
        "Medicine": "Amlodipine",
        "Diet": "Low salt diet",
        "Exercise": "Yoga",
        "Water": "2.5 Litres/day",
        "Precautions": "Reduce salt intake"
    }
}

print("Recommendation database created successfully!")

Recommendation database created successfully!

## Step 6: Create Disease Mapping

The trained model predicts encoded disease labels. This step creates a mapping between encoded labels and disease names so that predictions can be displayed in a human-readable format.

In [7]:
# Get all unique diseases from the dataset
disease_names = sorted(df["disease"].unique())

# Create mapping
disease_mapping = {i: disease for i, disease in enumerate(disease_names)}

print("Total Diseases:", len(disease_mapping))
print(disease_mapping)

Total Diseases: 116
{0: np.int64(0), 1: np.int64(1), 2: np.int64(2), 3: np.int64(3), 4: np.int64(4), 5: np.int64(5), 6: np.int64(6), 7: np.int64(7), 8: np.int64(8), 9: np.int64(9), 10: np.int64(10), 11: np.int64(11), 12: np.int64(12), 13: np.int64(13), 14: np.int64(14), 15: np.int64(15), 16: np.int64(16), 17: np.int64(17), 18: np.int64(18), 19: np.int64(19), 20: np.int64(20), 21: np.int64(21), 22: np.int64(22), 23: np.int64(23), 24: np.int64(24), 25: np.int64(25), 26: np.int64(26), 27: np.int64(27), 28: np.int64(28), 29: np.int64(29), 30: np.int64(30), 31: np.int64(31), 32: np.int64(32), 33: np.int64(33), 34: np.int64(34), 35: np.int64(35), 36: np.int64(36), 37: np.int64(37), 38: np.int64(38), 39: np.int64(39), 40: np.int64(40), 41: np.int64(41), 42: np.int64(42), 43: np.int64(43), 44: np.int64(44), 45: np.int64(45), 46: np.int64(46), 47: np.int64(47), 48: np.int64(48), 49: np.int64(49), 50: np.int64(50), 51: np.int64(51), 52: np.int64(52), 53: np.int64(53), 54: np.int64(54), 55: np.int64(55), 56: np.int64(56), 57: np.int64(57), 58: np.int64(58), 59: np.int64(59), 60: np.int64(60), 61: np.int64(61), 62: np.int64(62), 63: np.int64(63), 64: np.int64(64), 65: np.int64(65), 66: np.int64(66), 67: np.int64(67), 68: np.int64(68), 69: np.int64(69), 70: np.int64(70), 71: np.int64(71), 72: np.int64(72), 73: np.int64(73), 74: np.int64(74), 75: np.int64(75), 76: np.int64(76), 77: np.int64(77), 78: np.int64(78), 79: np.int64(79), 80: np.int64(80), 81: np.int64(81), 82: np.int64(82), 83: np.int64(83), 84: np.int64(84), 85: np.int64(85), 86: np.int64(86), 87: np.int64(87), 88: np.int64(88), 89: np.int64(89), 90: np.int64(90), 91: np.int64(91), 92: np.int64(92), 93: np.int64(93), 94: np.int64(94), 95: np.int64(95), 96: np.int64(96), 97: np.int64(97), 98: np.int64(98), 99: np.int64(99), 100: np.int64(100), 101: np.int64(101), 102: np.int64(102), 103: np.int64(103), 104: np.int64(104), 105: np.int64(105), 106: np.int64(106), 107: np.int64(107), 108: np.int64(108), 109: np.int64(109), 110: np.int64(110), 111: np.int64(111), 112: np.int64(112), 113: np.int64(113), 114: np.int64(114), 115: np.int64(115)}

## Step 7: Predict Disease

This function accepts patient information, predicts the disease using the trained Random Forest model, and returns the predicted disease label.

In [18]:
def predict_disease(patient_data):

    patient_df = pd.DataFrame([patient_data])

    prediction = model.predict(patient_df)

    disease = label_encoder.inverse_transform(prediction)[0]

    return disease

In [9]:
patient = {
    "fever": 1,
    "cough": 1,
    "fatigue": 1,
    "difficulty_breathing": 0,
    "age": 35,
    "gender": 1,
    "blood_pressure": 120,
    "cholesterol_level": 180,
    "age_scaled": 0.35,
    "bp_scaled": 0.45,
    "chol_scaled": 0.40,
    "risk_level": 1
}

patient_df = pd.DataFrame([patient])

patient_df

,fever,cough,fatigue,difficulty_breathing,age,gender,blood_pressure,cholesterol_level,age_scaled,bp_scaled,chol_scaled,risk_level
0,1,1,1,0,35,1,120,180,0.35,0.45,0.4,1

In [10]:
predicted_disease = model.predict(patient_df)[0]

print("Predicted Disease:", predicted_disease)

Predicted Disease: 101

## Step 8: Test Prediction

A sample patient record is used to test the trained model.

In [11]:
print(feature_names)

['fever' 'cough' 'fatigue' 'difficulty_breathing' 'age' 'gender'
 'blood_pressure' 'cholesterol_level' 'age_scaled' 'bp_scaled'
 'chol_scaled' 'risk_level']

In [19]:
patient = {
    "fever": 1,
    "cough": 1,
    "fatigue": 1,
    "difficulty_breathing": 0,
    "age": 35,
    "gender": 1,
    "blood_pressure": 120,
    "cholesterol_level": 180,
    "age_scaled": 0.35,
    "bp_scaled": 0.45,
    "chol_scaled": 0.40,
    "risk_level": 1
}

predicted_disease = predict_disease(patient)

print("Predicted Disease:", predicted_disease)

Predicted Disease: Stroke

## Step 9: Medicine Recommendation Database

Create a medicine recommendation database that stores medicines, diet plans, exercise suggestions, water intake, and precautions for different diseases. Based on the predicted disease, the system retrieves personalized healthcare recommendations.

In [20]:
recommendation_db = {

    "Stroke": {
    "Medicine": "Aspirin",
    "Diet": "Low fat, low salt diet",
    "Exercise": "Physiotherapy and light walking",
    "Water": "2.5 Litres/day",
    "Precautions": "Monitor blood pressure and avoid smoking"
},

    "Influenza": {
        "Medicine": "Paracetamol",
        "Diet": "Warm soup, citrus fruits, vegetables",
        "Exercise": "Complete rest",
        "Water": "3 Litres/day",
        "Precautions": "Wear a mask and take proper rest"
    },

    "Common Cold": {
        "Medicine": "Cetirizine",
        "Diet": "Vitamin C rich fruits",
        "Exercise": "Light walking",
        "Water": "2.5 Litres/day",
        "Precautions": "Avoid cold drinks"
    },

    "Asthma": {
        "Medicine": "Salbutamol Inhaler",
        "Diet": "Fresh fruits and vegetables",
        "Exercise": "Breathing exercises",
        "Water": "3 Litres/day",
        "Precautions": "Avoid dust and smoke"
    },

    "Diabetes": {
        "Medicine": "Metformin",
        "Diet": "Low sugar diet",
        "Exercise": "30 minutes walking",
        "Water": "2.5 Litres/day",
        "Precautions": "Monitor blood sugar regularly"
    },

    "Hypertension": {
        "Medicine": "Amlodipine",
        "Diet": "Low salt diet",
        "Exercise": "Yoga",
        "Water": "2.5 Litres/day",
        "Precautions": "Reduce salt intake"
    }

}

print("Recommendation database created successfully!")

Recommendation database created successfully!

## Step 10: Display Healthcare Recommendation

Display personalized healthcare recommendations based on the predicted disease. The system shows medicines, diet plans, exercise routines, water intake, and precautions.

In [21]:
predicted_disease = predict_disease(patient)

if predicted_disease in recommendation_db:

    result = recommendation_db[predicted_disease]

    print("=" * 60)
    print("🏥 PERSONALIZED HEALTHCARE REPORT")
    print("=" * 60)

    print("Disease      :", predicted_disease)
    print("Medicine     :", result["Medicine"])
    print("Diet         :", result["Diet"])
    print("Exercise     :", result["Exercise"])
    print("Water Intake :", result["Water"])
    print("Precautions  :", result["Precautions"])

else:
    print("No recommendation available for:", predicted_disease)

============================================================
🏥 PERSONALIZED HEALTHCARE REPORT
============================================================
Disease      : Stroke
Medicine     : Aspirin
Diet         : Low fat, low salt diet
Exercise     : Physiotherapy and light walking
Water Intake : 2.5 Litres/day
Precautions  : Monitor blood pressure and avoid smoking

In [15]:
print(df["disease"].unique())

[ 56  24  37   6  53   1   4  32  42  81  92  31  60 101 112  30  48  57
  69  72  98 111   9  13  15  23  52  70  73 113  77  84   7  21  39  51
  74  90  93  22  25  61  65 100  58  75  59   0  11  28  43  91  16  26
  35  41  46  54  64 108  62  55   8  27  50  68  79 109 115  14  83  95
  97 104   3  18  38  96  99  34  36  63  80  85   5  40  45  66  82  47
  87 102 110  12  67  76  86  19  49  88 105  10  78 107   2  20  29  33
  71  17  89  94  44 103 106 114]

In [16]:
print(sorted(df["disease"].unique()))

[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24), np.int64(25), np.int64(26), np.int64(27), np.int64(28), np.int64(29), np.int64(30), np.int64(31), np.int64(32), np.int64(33), np.int64(34), np.int64(35), np.int64(36), np.int64(37), np.int64(38), np.int64(39), np.int64(40), np.int64(41), np.int64(42), np.int64(43), np.int64(44), np.int64(45), np.int64(46), np.int64(47), np.int64(48), np.int64(49), np.int64(50), np.int64(51), np.int64(52), np.int64(53), np.int64(54), np.int64(55), np.int64(56), np.int64(57), np.int64(58), np.int64(59), np.int64(60), np.int64(61), np.int64(62), np.int64(63), np.int64(64), np.int64(65), np.int64(66), np.int64(67), np.int64(68), np.int64(69), np.int64(70), np.int64(71), np.int64(72), np.int64(73), np.int64(74), np.int64(75), np.int64(76), np.int64(77), np.int64(78), np.int64(79), np.int64(80), np.int64(81), np.int64(82), np.int64(83), np.int64(84), np.int64(85), np.int64(86), np.int64(87), np.int64(88), np.int64(89), np.int64(90), np.int64(91), np.int64(92), np.int64(93), np.int64(94), np.int64(95), np.int64(96), np.int64(97), np.int64(98), np.int64(99), np.int64(100), np.int64(101), np.int64(102), np.int64(103), np.int64(104), np.int64(105), np.int64(106), np.int64(107), np.int64(108), np.int64(109), np.int64(110), np.int64(111), np.int64(112), np.int64(113), np.int64(114), np.int64(115)]